repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.9.3'
    hooks:
      - id: isort
        args: [
          "--settings=./bot_telegram/pyproject.toml"
        ]
  - repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
        args: [
          "--config=./bot_telegram/pyproject.toml"
        ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff
        args: [
          "--config=./bot_telegram/pyproject.toml"
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
      - id: mypy
        additional_dependencies: [
          tokenize-rt == 3.2.0,
        ]
        args: [
          --no-strict-optional,
          --ignore-missing-imports,
          "--config-file=./bot_telegram/pyproject.toml",
        ]


