# Generated by Django 4.2.3 on 2023-08-06 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0002_remove_client_is_active_alter_client_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.AddField(
            model_name='client',
            name='user_id',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Responce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('yes', 'Записатись'), ('maybe', 'Можливо буду'), ('no', 'Не прийду')], max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meets.client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meets.event')),
            ],
        ),
    ]
