# Generated by Django 4.2.3 on 2023-08-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0003_remove_client_is_admin_remove_client_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='description',
        ),
    ]
